version: '3.9'
services:
  postgres-pytest:
    image: postgres:14
    container_name: didier-pytest
    restart: always
    environment:
      - POSTGRES_DB=didier_pytest
      - POSTGRES_USER=pytest
      - POSTGRES_PASSWORD=pytest
    ports:
      - "5433:5432"
