version: '3.9'
services:
  db:
    image: postgres:14
    container_name: didier
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-didier_dev}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
