version: '3.9'
services:
  db:
    image: postgres:14
    container_name: didier
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-didier_dev}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - db:/var/lib/postgresql/data
  db-pytest:
    image: postgres:14
    container_name: didier-pytest
    restart: always
    environment:
      - POSTGRES_DB=didier_pytest
      - POSTGRES_USER=pytest
      - POSTGRES_PASSWORD=pytest
    ports:
      - "5433:5432"
volumes:
  db:
