[tool.black]
line-length = 120

[tool.coverage.run]
concurrency = [
    "greenlet"
]
source = [
    "didier",
    "database"
]
omit = [
    "./tests/*",
    "./database/migrations.py",
    "./didier/cogs/*",
    "./didier/didier.py",
    "./didier/data/constants.py",
    "./didier/data/embeds/*",
    "./didier/data/flags/*",
    "./didier/utils/discord/colours.py",
    "./didier/utils/discord/constants.py",
    "./didier/utils/discord/flags/*",
]

[tool.isort]
profile = "black"

[tool.mypy]
files = [
    "database/**/*.py",
    "didier/**/*.py",
    "main.py"
]
plugins = [
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin"
]
[[tool.mypy.overrides]]
module = ["discord.*", "feedparser.*", "markdownify.*", "motor.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
env = [
    "MONGO_DB = didier_pytest",
    "MONGO_USER = pytest",
    "MONGO_PASS = pytest",
    "MONGO_HOST = localhost",
    "MONGO_PORT = 27018",
    "POSTGRES_DB = didier_pytest",
    "POSTGRES_USER = pytest",
    "POSTGRES_PASS = pytest",
    "POSTGRES_HOST = localhost",
    "POSTGRES_PORT = 5433",
    "DISCORD_TOKEN = token"
]
