[tool.black]
line-length = 120

[tool.coverage.run]
concurrency = [
    "greenlet"
]
source = [
    "didier",
    "database"
]
omit = [
    "./tests/*",
    "./database/migrations.py",
    "./didier/cogs/*",
    "./didier/didier.py",
    "./didier/data/*",
    "./didier/utils/discord/colours.py",
    "./didier/utils/discord/constants.py"
]

[tool.isort]
profile = "black"

[tool.mypy]
plugins = [
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin"
]
[[tool.mypy.overrides]]
module = ["discord.*", "feedparser.*", "markdownify.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
env = [
    "DB_NAME = didier_pytest",
    "DB_USERNAME = pytest",
    "DB_PASSWORD = pytest",
    "DB_HOST = localhost",
    "DB_PORT = 5433",
    "DISCORD_TOKEN = token"
]
