[tool.black]
line-length = 120

[tool.mypy]
plugins = [
    "sqlalchemy.ext.mypy.plugin"
]

[tool.pylint.master]
disable = [
    "missing-module-docstring",
    "too-few-public-methods",
    "too-many-arguments"
]

[tool.pylint.format]
max-line-length = 120
good-names = ["i"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
env = [
    "DB_NAME = didier-tests",
    "DB_USERNAME = postgres",
    "DB_HOST = postgres",
    "DISC_TOKEN = token"
]