"""Add second role to ufora courses

Revision ID: 11388e39bb90
Revises: a64876b41af2
Create Date: 2022-09-25 00:09:06.625622

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "11388e39bb90"
down_revision = "a64876b41af2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ufora_courses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alternative_overarching_role_id", sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ufora_courses", schema=None) as batch_op:
        batch_op.drop_column("alternative_overarching_role_id")

    # ### end Alembic commands ###
