"""Add free games

Revision ID: 9fb84b4d9f0b
Revises: 11388e39bb90
Create Date: 2022-10-13 19:17:58.032182

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9fb84b4d9f0b"
down_revision = "11388e39bb90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "free_games", sa.Column("free_game_id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("free_game_id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("free_games")
    # ### end Alembic commands ###
