"""Add option to disable announcement fetching for courses

Revision ID: d3cd92cb9efe
Revises: 9e8ce58c0a26
Create Date: 2022-06-18 00:36:00.484627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3cd92cb9efe"
down_revision = "9e8ce58c0a26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ufora_courses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("log_announcements", sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ufora_courses", schema=None) as batch_op:
        batch_op.drop_column("log_announcements")

    # ### end Alembic commands ###
